vich_uploader:
    db_driver: orm
    storage: filesystem

    mappings:
        default:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

